<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>erazor</string>
		<string>ehtml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>^\s*\}$</string>
	<key>name</key>
	<string>Erazor (HTML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#else</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#partials</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scriptblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>scriptblock</key>
		<dict>
			<key>begin</key>
			<string>@\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>source.hscript</string>
			<key>beginCaptures</key>
	          <dict>
	            <key>0</key>
	            <dict>
	              <key>name</key>
	              <string>entity.name.tag.erazor</string>
	            </dict>
	          </dict>
	        <key>endCaptures</key>
	          <dict>
	            <key>0</key>
	            <dict>
	              <key>name</key>
	              <string>entity.name.tag.erazor</string>
	            </dict>
	          </dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#codeblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.haxe.2</string>
				</dict>
			</array>
		</dict>
		<key>control</key>
		<dict>
			<key>begin</key>
			<string>(@)([a-zA-Z.]+)?(\()</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>source.erazor</string>
			<key>beginCaptures</key>

	          <dict>
	          	<key>1</key>
	            <dict>
	              <key>name</key>
	              <string>punctuation.erazor.start</string>
	            </dict>
	            <key>2</key>
	            <dict>
	              <key>name</key>
	              <string>entity.name.function.erazor</string>
	            </dict>
	            <key>3</key>
	            <dict>
	              <key>name</key>
	              <string>punctuation.erazor.parenthesis</string>
	            </dict>
	           </dict>
	          
	        <key>endCaptures</key>
	          <dict>
	            <key>0</key>
	            <dict>
	              <key>name</key>
	              <string>punctuation.erazor.parenthesis</string>
	            </dict>
	          </dict>

			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.haxe.2</string>
				</dict>
	
			</array>
		</dict>
		<key>codeblock</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>source.erazor</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#codeblock</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.haxe.2</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(@)([A-Za-z0-9_.]+)</string>
					<key>name</key>
					<string>source.erazor</string>
					<key>captures</key>
			          <dict>
			          	<key>1</key>
			            <dict>
			              <key>name</key>
			              <string>punctuation.erazor.start</string>
			            </dict>
			            <key>2</key>
			            <dict>
			              <key>name</key>
			              <string>entity.name.variable.erazor</string>
			            </dict>
			          </dict>
				</dict>
			</array>
		</dict>
		<key>else</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\}(else)\{</string>
					<key>name</key>
					<string>source.erazor</string>
					<key>captures</key>
			          <dict>
			          	<key>1</key>
			            <dict>
			              <key>name</key>
			              <string>entity.name.function.erazor</string>
			            </dict>
			            
			          </dict>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.erazor</string>
	<key>uuid</key>
	<string>93706aaa-9b66-4e9e-bb64-31a8ffcfb00e</string>
</dict>
</plist>